### ISSUE TITLE
Add extras-scala-io

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/extras#24]
# Task
## Summary
Add `extras-scala-io`

## Project Details
Version: `0.1.0`

## Description
It should have.
- [x] Typed version of `scala.io.AnsiColor` (#26)
- [x] `ColorSyntax` for typed `AnsiColor` (#27)
- [x] `CanClose[A]` type class as an alternative to `AutoCloseable` (#28)
- [x] Write `CanClose` type class instance for `scala.io.Source` (#29)
